# Generated by Django 3.2.3 on 2021-05-27 10:06

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='src',
            field=models.FileField(blank=True, null=True, upload_to=polls.models.article),
        ),
    ]
